version: '3.6'
services:
  tunachain-db:
    image: postgres
    container_name: tunachain-db
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db-data-test:/var/lib/postgresql/data
      - ./postgres/init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 5

  tunachain-backend:
    build:
      context: .
      target: development
      dockerfile: ./backend/Dockerfile
    image: hyperledger/tunachain-backend
    container_name: tunachain-backend
    volumes:
      - ./backend:/project/sawtooth-tuna/backend
      - /project/sawtooth-tuna/backend/node_modules
    command: npm run test:e2e
    ports:
      - 3001:3001
      - 9229:9229
    depends_on:
      tunachain-db:
        condition: service_healthy