export const RouteUrl = {
    home: '/',
    signup: '/auth/signup',
    login: '/auth/login',
    trip: '/trip',
    haul: '/haul',
    pallet: '/pallet',
    product: '/product',
    palletEvent: '/palletEvent',
    catch: '/catch',
    species: '/species',
    company: '/company',
    consumerPackage: '/consumerPackage',
    viewConsumerPackage: '/viewConsumerPackage',
    production: '/production',
};
